### ISSUE TITLE
Compose does not run in correct isolation mode

### ISSUE THREAD

**Issue by asdkant-bf** [slonopotamus/stevedore#69]
### Stevedore Version

2.4.0

### What steps are needed to reproduce the behavior?

context: I'm trying to run an image based on windows 2019 in a host with windows 2022, so I enabled Hyper-V.

1. run this to confirm that Hyper-V isolation works:
```powershell
docker run -it --isolation=hyperv mcr.microsoft.com/windows/nanoserver:ltsc2019 cmd
```

2. start this compose project:
```yaml
version: '2.4'
services:
  traefik:
    image: stefanscherer/traefik-windows
    command: --docker.endpoint=npipe:////./pipe/docker_engine --logLevel=DEBUG
    ports:
      - "8080:8080" # Please read: https://docs.traefik.io/configuration/api/#security
      - "443:443"
      - "80:80"
    isolation: process # workaround for https://github.com/containous/traefik/issues/4409
    volumes:
      - .:C:/etc/traefik
      - type: npipe
        source: \\.\pipe\docker_engine
        target: \\.\pipe\docker_engine

  whoami1:
    image: stefanscherer/whoami
    isolation: hyperv
    labels:
      - "traefik.backend=whoami"
      - "traefik.frontend.entryPoints=http"
      - "traefik.frontend.rule=Host:whoami.docker.local"

  whoami2:
    image: stefanscherer/whoami
    isolation: hyperv
    labels:
      - "traefik.backend=whoami"
      - "traefik.frontend.entryPoints=http"
      - "traefik.frontend.rule=Host:whoami.docker.local"

#  portainer:
#    image: portainer/portainer
#    labels:
#      - "traefik.backend=portainer"
#      - "traefik.frontend.rule=Host:portainer.yourdomain.com"

networks:
  default:
    external:
      name: nat
```

### What you expected?

First step should work giving the user a prompt inside the container.

Second step should start the compose project.

### What happened?

I got this error message when trying to start the compose project:
```
no matching manifest for windows/amd64 10.0.20348 in the manifest list entries
```

### Additional context

I also opened an issue in the compose repo: https://github.com/docker/compose/issues/12481

I'm assuming a workaround would be to set the docker daemon to use Hyper-V isolation by default but I can't find where the config file is supposed to be.
